### PR TITLE
Django1.10

### PR DESCRIPTION
**Pull request by eracle**
Django 1.10 upgraded

### CODE REVIEW

**Comment by maxolasersquad** [comment]
All of these changes look good, and I really appreciate you taking the time to do this.

Before I merge this in, are these changes backwards compatible to Django 1.8? I'm wondering if we shouldn't just bump the requirements up to 1.10.

**Comment by eracle** [comment]
No, as I just tried, with django 1.8 it tries to load the static files from a different directory, this is the runserver log ( the 404 responses are the errors):

[16/Sep/2016 09:02:36]"GET /register/ HTTP/1.1" 200 6596
[16/Sep/2016 09:02:36]"GET /static/js/require.js HTTP/1.1" 304 0
[16/Sep/2016 09:02:36]"GET /static/register/css/register.css HTTP/1.1" 304 0
[16/Sep/2016 09:02:36]"GET /css/bootstrap.min.css HTTP/1.1" 404 18633
[16/Sep/2016 09:02:36]"GET /css/font-awesome.css HTTP/1.1" 404 18630
[16/Sep/2016 09:02:36]"GET /css/bootstrap-theme.min.css HTTP/1.1" 404 18651
[16/Sep/2016 09:02:36]"GET /static/register/js/register.js HTTP/1.1" 304 0


I would propose to bump the requirements to 1.10

**Comment by maxolasersquad** [comment]
If you don't mind adding the version bump and then I'll merge this in.

**Comment by eracle** [comment]
sure, I'll it

**Pull request merged**
